"""Add cascades and check constraints

Revision ID: 956ba07e9519
Revises: 63790647ce31
Create Date: 2026-08-09 13:53:09.185004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956ba07e9519'
down_revision: Union[str, Sequence[str], None] = '63790647ce31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workout_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'])

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'])
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'])

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
